// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ruH1utS1tKKzLM5ecUVncTZqM8_rqk0',
    appId: '1:1010142713571:web:0940ac365b0ae309fb57d6',
    messagingSenderId: '1010142713571',
    projectId: 'robocon-2023',
    authDomain: 'robocon-2023.firebaseapp.com',
    storageBucket: 'robocon-2023.appspot.com',
    measurementId: 'G-P43YJSY7MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh-HD5n3OJAvnAcwqYLn5mRYD2S1QAqeY',
    appId: '1:1010142713571:android:b6fb960085e7b579fb57d6',
    messagingSenderId: '1010142713571',
    projectId: 'robocon-2023',
    storageBucket: 'robocon-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJeGwycd_uK52mWI3W6fSKh3EIzeWzaXs',
    appId: '1:1010142713571:ios:cffd28c99bb707e2fb57d6',
    messagingSenderId: '1010142713571',
    projectId: 'robocon-2023',
    storageBucket: 'robocon-2023.appspot.com',
    iosClientId: '1010142713571-9itkldaqfp5c1hkhqs4hnso416rljqbu.apps.googleusercontent.com',
    iosBundleId: 'com.fsm.roboconAdmin2023',
  );
}
